### ISSUE TITLE
Add cost to LSP Object

### ISSUE THREAD

**Issue by cpmarvin** [tim-fiola/network_traffic_modeler_py3#24]
Hello,

Feature request to add cost to LSP object. This will help with LSP between two host that have different metric( corner case i know).
It will also help with equal cost LSP later in the simulation if there is a need to load balance across LSP. 

Regards,

**Comment by tim-fiola** [comment]
Hi.  The default behavior in pyNTM is the same as in RSVP: the LSP will always inherit the shortest path cost, regardless of the actual path.  So you can still have load balancing across parallel LSPs (those with the same source and destination) regardless of any those LSP's particular path.  

Or, are you asking that the model support a user-assigned (manual) metric?

Please advise.

Thank you!

**Comment by cpmarvin** [comment]
I agree about the implicit cost following the SPF , I was after use-assigned metric. Considering a scenario where you only want to use specific LSP's if others are down , then someone might have LSP1(A-C) metric 10 , LSP2(A-C) metric 15, IGP COST A-C = 20 .When both are up , LSP1 should take traffic but not LSP2.

But then again , you would probably not engineer the network like that in the first place. 

Thx.

**Comment by tim-fiola** [comment]
So this is something that I'd likely do if a user or potential user asked for it.  I'm not sure if it makes sense to do this until I have a real use case to do so because, as you said, I'm not certain that'd be something someone would do.  

If there is practical demand for this, however, I'm happy to add it!

**Comment by tim-fiola** [comment]
under development now

**Comment by tim-fiola** [comment]
implemented in 2.1
