### ISSUE TITLE
Support for IGP shortcuts in Demand

### ISSUE THREAD

**Issue by cpmarvin** [tim-fiola/network_traffic_modeler_py3#25]
Hello,

Feature request

Add support for IGP shortcuts in the model demand. This will help with networks that have a mix of RSVP-LSP and LDP based traffic where only the core is RSVP and the rest is still LDP( IGP routed).  In the current implementation if we have a topology A-B-C , where there is a LSP from A-B but the demand is A-C the model will not put traffic on the LSP but rather use the IGP shortest path between A-C.

Having a LSP flag ( shortcut ) will help in simulating this scenario , where maybe the model will look at the path between A-C , the LSP objects that start at A and have a tailend destination in the A-C path and use that LSP ( A-B) then switch to IGP shortest path once B is reached( ie: B-C will still be igp routed). 

Hope this makes sense. 

Regards,

**Comment by tim-fiola** [comment]
Acknowledged.  Let me take some time on how to architect this feature.  This makes sense though.

**Comment by tim-fiola** [comment]
Looking at how to implement this.  Initial thoughts.  Please comment if you see anything that does not look correct.

From https://www.juniper.net/documentation/en_US/junos/topics/concept/mpls-igp-shortcuts-igp-routing-table.html: 
_The list of destinations whose shortest path traverses the egress router (established during the first computation) is placed in the inet.3 routing table.  These destinations are given the egress router of the LSP as a next hop, enabling BGP on the local router to use these LSPs to access BGP next hops beyond the egress router._ 

In the model, then:
1. From a demand's source, compute all **shortest** paths to destination
2. For each shortest path:
- At any given hop on a shortest path, the demand should 
  - look for LSPs to downstream hops on the shortest path and prefer those LSPs over physical interfaces
  - prefer LSPs that can bring it closest to its destination on the shortest path
  - if no LSP to a downstream hop on the shortest path is present, proceed to next node via Interface

**Comment by cpmarvin** [comment]
Hi Tim,

I would say per-node only is the most common case i saw. This looks fine , only question from my side, when you say  

> look for LSPs to downstream hops on the shortest path and prefer those LSPs over physical interfaces

i'm assuming it takes into account _only_ LSP with headend == the node you are in the shortest at that stage.

**Comment by tim-fiola** [comment]
Scoping this for implementation in 1.7

**Comment by tim-fiola** [comment]
under development now

**Comment by tim-fiola** [comment]
Implemented in 2.1
