### ISSUE TITLE
Feature request: L2/STP support 

### ISSUE THREAD

**Issue by ggiesen** [tim-fiola/network_traffic_modeler_py3#31]
I know this request is a bit groan-inducing... but any interest in modeling L2/STP?

**Comment by tim-fiola** [comment]
Hi.  The short story is that I can't support that: that would be a different project and one that would model a technology that, while mature, I'm not terribly familiar with.  Do you mind if I ask what the use case is to model that?

**Comment by tim-fiola** [comment]
This would be beyond the scope of what I can support
