### ISSUE TITLE
total capacity between nodes

### ISSUE THREAD

**Issue by mingbocui** [tim-fiola/network_traffic_modeler_py3#45]
Hi,

I am working with a network that some edges are uni-directional but some are bi-directional that also have a sum capacity,  For example, if node A and node B is connected with an edge, flow from A to B and from B to A are all possible through this edge,  this edge did not have a directional capacity but have a sum capacity, namely the **sum** of flow **from A to B** and flow **from B to A** can not exceed the capacity. could I find a solution to model this in pyNTM? 

Thanks a lot!

**Comment by tim-fiola** [comment]
Hi Mingbo.  What type of network interface is that?  Is it a multi-access
link?

pyNTM is specifically designed to model point to point links; it requires 2
component Interfaces to be paired into a Circuit and so both Interfaces
must have matching capacity.

I am not seeing a way to do what you need to do with the code as it is.
You'd have to create a patch for that Interface that would sum up the
traffic and ensure it was below the limit.  If you're experienced in python
that should be fairly straightforward.  There are no plans right now to add
that capability to the core code.

Hope this helps.

Thanks!
